"use client";

import { Button, buttonVariants } from "@/components/ui/button";
import { Metadata } from "next";
import Link from "next/link";
import { useEffect, useState } from "react";

export const metadata: Metadata = {
  title: "Odinus UI",
  description: "Generated by create next app",
};

export default function NotFound() {
  const [path, setPath] = useState("");
  useEffect(() => {
    const newPath = window.location.pathname;
    setPath(newPath);
  }, []);

  return (
    <main className="pt-10 text-center h-[100vh] flex flex-col justify-center">
      <h1 className="font-bold text-xl mb-5">404: Page Not Found</h1>
      <div>
        <p>We couldn't find the page {path}.</p>
        <p>Check the URL and try again.</p>
      </div>
      <div className="flex gap-1 justify-center mt-5">
        <Link href={"/"} className={buttonVariants({ size: "sm" })}>
          Home
        </Link>
        <Link
          href={"https://odinus.shop/"}
          className={buttonVariants({ variants: "outline", size: "sm" })}
        >
          odinus.shop
        </Link>
      </div>
    </main>
  );
}
